{
  wayland.windowManager.hyprland.settings = {
    bind = [
      "$mainMod, RETURN, exec, $terminal"
      "$mainMod+SHIFT, F, exec, $browser"
      "$mainMod+SHIFT, T, exec, $fileManager"
      "$mainMod, R, exec, $launcher"
      "$mainMod, P, exec, $powermenu"
      "$mainMod, Q, killactive,"
      "$mainMod+$altMod, Q, exit,"
      "$mainMod, E, togglefloating,"
      "$mainMod+SHIFT, E, pin, active"
      "$mainMod, X, togglesplit,"
      "$mainMod, M, fullscreen, 0"
      "$mainMod, H, movefocus, l"
      "$mainMod, L, movefocus, r"
      "$mainMod, K, movefocus, u"
      "$mainMod, J, movefocus, d"
      "$mainMod+SHIFT, H, movewindow, l"
      "$mainMod+SHIFT, L, movewindow, r"
      "$mainMod+SHIFT, K, movewindow, u"
      "$mainMod+SHIFT, J, movewindow, d"
      "$mainMod, 1, workspace, 1"
      "$mainMod, 2, workspace, 2"
      "$mainMod, 3, workspace, 3"
      "$mainMod, 4, workspace, 4"
      "$mainMod, 5, workspace, 5"
      "$mainMod, 6, workspace, 6"
      "$mainMod, 7, workspace, 7"
      "$mainMod, 8, workspace, 8"
      "$mainMod, 9, workspace, 9"
      "$mainMod, 0, workspace, 10"
      "$mainMod $controlMod, 1, movetoworkspacesilent, 1"
      "$mainMod $controlMod, 2, movetoworkspacesilent, 2"
      "$mainMod $controlMod, 3, movetoworkspacesilent, 3"
      "$mainMod $controlMod, 4, movetoworkspacesilent, 4"
      "$mainMod $controlMod, 5, movetoworkspacesilent, 5"
      "$mainMod $controlMod, 6, movetoworkspacesilent, 6"
      "$mainMod $controlMod, 7, movetoworkspacesilent, 7"
      "$mainMod $controlMod, 8, movetoworkspacesilent, 8"
      "$mainMod $controlMod, 9, movetoworkspacesilent, 9"
      "$mainMod $controlMod, 0, movetoworkspacesilent, 10"
      "$mainMod SHIFT, 1, movetoworkspace, 1"
      "$mainMod SHIFT, 2, movetoworkspace, 2"
      "$mainMod SHIFT, 3, movetoworkspace, 3"
      "$mainMod SHIFT, 4, movetoworkspace, 4"
      "$mainMod SHIFT, 5, movetoworkspace, 5"
      "$mainMod SHIFT, 6, movetoworkspace, 6"
      "$mainMod SHIFT, 7, movetoworkspace, 7"
      "$mainMod SHIFT, 8, movetoworkspace, 8"
      "$mainMod SHIFT, 9, movetoworkspace, 9"
      "$mainMod SHIFT, 0, movetoworkspace, 10"
      "$mainMod, S, togglespecialworkspace, magic"
      "$mainMod SHIFT, S, movetoworkspace, special:magic"

      "$altMod, w, exec, bash /nixos-config/users/\${USER}/bin/change_wallpaper.sh"
      "$altMod, b, exec, pkill waybar || waybar"
      ", PRINT, exec, hyprshot -m region"
    ];
    bindm = [
      "$mainMod, mouse:272, movewindow"
      "$mainMod, mouse:273, resizewindow"
    ];
    bindl = [
      ", XF86AudioNext, exec, playerctl next"
      ", XF86AudioPause, exec, playerctl play-pause"
      ", XF86AudioPlay, exec, playerctl play-pause"
      ", XF86AudioPrev, exec, playerctl previous"
    ];

  };
}
